In [1]:
import pandas as pd
import numpy as np
import kagglehub

c:\Users\fbase\All_vscode_projects\PandasGithubRepo\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
path = kagglehub.dataset_download("sumit17125/red-wine-quality-dataset")
df = pd.read_csv(path + "/winequality-red.csv",sep=";")

In [3]:
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

Problem 1 — Distribution Logic

Identify the top 10% of rows based on the target variable (quality, score, price, etc.).

Create a new dataset that contains only those rows.

Then compute:

- mean of every feature
- variance of every feature

Compare them with the means and variances of the full dataset.

In [4]:
# Assuming it means top 10% highest quality 
top10Percent = int(df.shape[0] * 10/100)
sortedi = np.argsort(df['quality'])[df.shape[0] - top10Percent:]
df2 = df.iloc[sortedi]
df2

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
1125,8.8,0.24,0.35,1.7,0.055,13.0,27.0,0.99394,3.14,0.59,11.3,7
1405,7.7,0.28,0.30,2.0,0.062,18.0,34.0,0.99520,3.28,0.90,11.3,7
259,10.0,0.31,0.47,2.6,0.085,14.0,33.0,0.99965,3.36,0.80,10.5,7
1134,8.5,0.28,0.35,1.7,0.061,6.0,15.0,0.99524,3.30,0.74,11.8,7
1133,7.2,0.48,0.07,5.5,0.089,10.0,18.0,0.99684,3.37,0.68,11.2,7
...,...,...,...,...,...,...,...,...,...,...,...,...
1090,10.0,0.26,0.54,1.9,0.083,42.0,74.0,0.99451,2.98,0.63,11.8,8
1120,7.9,0.54,0.34,2.5,0.076,8.0,17.0,0.99235,3.20,0.72,13.1,8
588,5.0,0.42,0.24,2.0,0.060,19.0,50.0,0.99170,3.72,0.74,14.0,8
828,7.8,0.57,0.09,2.3,0.065,34.0,45.0,0.99417,3.46,0.74,12.7,8
1549,7.4,0.36,0.30,1.8,0.074,17.0,24.0,0.99419,3.24,0.70,11.4,8

In [5]:
a = df2.agg(['mean','var'])
a

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
mean,8.754717,0.391289,0.370314,2.666981,0.073440,13.880503,34.383648,0.995746,3.288868,0.731195,11.585639,7.113208
var,3.777557,0.018282,0.033749,1.978222,0.000478,108.672339,1275.086060,0.000004,0.024447,0.014850,1.023655,0.101027

In [6]:
b = df.agg(['mean','var'])
b

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
mean,8.319637,0.527821,0.270976,2.538806,0.087467,15.874922,46.467792,0.996747,3.311113,0.658149,10.422983,5.636023
var,3.031416,0.032062,0.037947,1.987897,0.002215,109.414884,1082.102373,0.000004,0.023835,0.028733,1.135647,0.652168

In [7]:
df.agg(['min','max'])

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
min,4.6,0.12,0.0,0.9,0.012,1.0,6.0,0.99007,2.74,0.33,8.4,3
max,15.9,1.58,1.0,15.5,0.611,72.0,289.0,1.00369,4.01,2.00,14.9,8

In [8]:
#These have higher mean in top10 Percent
#fixed acidity , citric acid , residual sugar , sulphates , alcohol

#These have lower
#volatile acidity , chlorides ,free sulfur dioxide , total sulfur dioxide , density , pH
"""
d = {}
for i,j in zip(a,b):
    print(f"{i} :",a[i].iloc[0]-b[j].iloc[0])
    d[i]=np.abs(a[i].iloc[0]-b[j].iloc[0])
"""

'\nd = {}\nfor i,j in zip(a,b):\n    print(f"{i} :",a[i].iloc[0]-b[j].iloc[0])\n    d[i]=np.abs(a[i].iloc[0]-b[j].iloc[0])\n'

Problem 2 — Conditional Filtering

Find rows where:

• one feature is above its column median
• another feature is below its column mean

Create a dataset containing only those rows.

Then sort those rows by the difference between those two features.

In [18]:
beast = df.to_numpy()
beast

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]],
      shape=(1599, 12))

In [19]:
col_mean = np.mean(beast,axis=0)
col_median = np.median(beast,axis=0)
meanMask = beast < col_mean
meadianMask = beast > col_median

In [ ]:
#np.argwhere(meanMask==True)

array([[   0,    0],
       [   0,    2],
       [   0,    3],
       ...,
       [1598,    4],
       [1598,    6],
       [1598,    7]], shape=(11070, 2))

In [37]:
mi = pd.DataFrame(np.where(meanMask==True)).T
mi

          0  1
0         0  0
1         0  2
2         0  3
3         0  4
4         0  5
...     ... ..
11065  1598  0
11066  1598  1
11067  1598  4
11068  1598  6
11069  1598  7

[11070 rows x 2 columns]

In [54]:
mi.drop_duplicates(subset=0,keep='first',inplace=True)
mi = mi.to_numpy()
mi

array([[   0,    0],
       [   1,    0],
       [   2,    0],
       ...,
       [1596,    0],
       [1597,    0],
       [1598,    0]], shape=(1599, 2))

In [61]:
mdi = pd.DataFrame(np.where(meadianMask==True)).T
mdi.drop_duplicates(subset=0,keep='first',inplace=True)
mdi

         0  1
0        0  1
3        1  1
10       2  1
17       3  0
22       4  1
...    ... ..
8654  1594  1
8660  1595  1
8666  1596  3
8672  1597  1
8677  1598  2

[1598 rows x 2 columns]

In [63]:
c1 = beast[mi[:,0],mi[:,1]]
c1

array([7.4, 7.8, 7.8, ..., 6.3, 5.9, 6. ], shape=(1599,))

In [64]:
c2 = beast[mdi.iloc[:,0],mdi.iloc[:,1]]
c2

array([0.7  , 0.88 , 0.76 , ..., 2.3  , 0.645, 0.47 ], shape=(1598,))

In [69]:
c2 = np.append(c2,values=0)
c2

array([0.7  , 0.88 , 0.76 , ..., 0.645, 0.47 , 0.   ], shape=(1599,))

In [72]:
answer = pd.DataFrame({'BelowMean':c1.T,'AboveMedian':c2.T})
answer

      BelowMean  AboveMedian
0          7.40        0.700
1          7.80        0.880
2          7.80        0.760
3          0.28       11.200
4          7.40        0.700
...         ...          ...
1594       6.20        0.550
1595       5.90        2.300
1596       6.30        0.645
1597       5.90        0.470
1598       6.00        0.000

[1599 rows x 2 columns]

In [74]:
answer.iloc[(answer.iloc[:,0]-answer.iloc[:,1]).argsort()]

      BelowMean  AboveMedian
45          4.6       65.000
1131        5.9       57.000
634         7.9       46.000
218         7.5       44.000
90          7.9       42.000
...         ...          ...
500         7.8        0.081
22          7.9        0.106
27          7.9        0.106
1425        8.3        0.370
41         46.0        8.800

[1599 rows x 2 columns]

In [75]:
answer.agg(['min','max'])

     BelowMean  AboveMedian
min        0.0          0.0
max       46.0         65.0